language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.2"
  - "2.3"
  - "4.0"
  - "5.0"
before_install:
  - npm install -g grunt-cli
  - npm install coffee-script
before_script: grunt build
script: npm run-script test-cov
after_success:
  - test -e ./coverage/lcov.info && npm install codeclimate-test-reporter && codeclimate-test-reporter
    < ./coverage/lcov.info
notifications:
  email:
    - snowyu.lee@gmail.com
addons:
  code_climate:
    repo_token:
      secure: "ALXJIKVNpXCrQ0L1VpM21Izb6e07WhuqIP1LuVu8RLUUInANhudyrcoyYdjoEX5Hjz0K+Zm9DtpzSU38pCHuHQlC5Fg9vWbNyTzxegJyO2lyNxlnq/f0OObxgz9bsNstDo3gVN+pr3E1HWuInJg610X12Fz7hr+5nKvhwcoeplS1sIUtW0+vzfv+uE60Hsv9TPrcM/KkWk/IUwc+Cp/+6TeqWXsZRz+fWOq/1JNu2GS3UUeM4eYXgKiAyXrttXr4UUfgHpD1F8VsmVXOJTdDASSL+KwB3tCwZjdlRaRmtFtr0iOWS2AkgZ3UqFMuJDDhTkQOqizqlWUL3Jbbx6yqom61ZNy4+5iwRv+P1NaB2nHHQI8f2i7UivlA4C27GVIEv4okZURzOzSquOXTVw2ZvqwgMAN3XR7ObunpsGa0M1X95ewiuEyNWxvF9+0B24J5ySlpYOxyLgrYoMxQw++nuHBX/lBD6kOSfTHEi2+qce/QMQRoCTBeEDi+8Vf9QbDR5tC6Ci6Jt41iFVZXlFHqkEp009FqWYnjVeAZXDr3R38rAnIWQwwtrr07cIJkOYBJrEmCQgR9xhU1siC4JatfibE43rWpSvEXJg7VkHOaPcekDYU1fGZekMtNYhdP2cCVCFva/2z8Qstsn2EgMAD1x0m3Jw/U6CNIr+gUqRPZAKA="